export const hero = {
  eyebrow: "Senior Software Developer",
  title: "Paul-Valentin Mini",
  tagline: "Building frontend platforms from concept to full-rate production. Even yours.",
  cta: "Get in touch",
  location: "San Francisco, CA",
  email: "paul@emini.com",
  phone: "(415) 694-3616",
  linkedin: "https://www.linkedin.com/in/pvmini",
  github: "https://github.com/Laptopmini",
};

export const profileSummary =
  "Senior Software Developer with 10+ years of experience building at a global scale. Expert in React, Next.js, and modern JavaScript ecosystems, with a proven track record of overhauling developer consoles and building robust internal component libraries. Today, I dedicate my expertise almost exclusively to Applied AI, Prompt Engineering, and LLM integrations, building tools to accelerate developer workflows and bootstrap product integrations. I have a proven track record of leading complex, cross-functional projects from proof-of-concept to zero-break production releases for enterprise platforms like Samsung SmartThings.";

export const skills: { category: string; items: string[] }[] = [
  {
    category: "Frontend & Web",
    items: ["JavaScript", "TypeScript", "React", "Next.js", "HTML/CSS"],
  },
  {
    category: "AI & Machine Learning",
    items: [
      "Prompt Engineering",
      "AI Model Orchestration",
      "LLM Integration (Claude, OpenCode, LM Studio)",
      "Test-Driven Development",
      "Computer Vision (OpenCV, Tesseract)",
    ],
  },
  {
    category: "Infrastructure & DevOps",
    items: [
      "Docker",
      "Kubernetes",
      "Terraform",
      "GitHub Actions",
      "Jenkins",
      "Spinnaker",
      "JFrog Artifactory (NPM)",
    ],
  },
  {
    category: "Backend & Mobile",
    items: ["Python", "Swift", "PostgreSQL", "REST API Design", "iOS/Android Development"],
  },
];

export const experience: {
  company: string;
  location: string;
  role: string;
  period: string;
  bullets: string[];
  stack: string[];
}[] = [
  {
    company: "SmartThings, Inc.",
    location: "San Francisco, CA",
    role: "Senior Software Developer",
    period: "January 2020 – Present",
    bullets: [
      "Frontend Architecture & Global Leadership: Lead developer for the SmartThings Developer Console, unifying UX across multiple web products while partnering with global teams (Poland, Indonesia, Korea) to integrate cross-functional features.",
      "AI Integration & Tooling: Actively contributed to the company's AI pilot program as a designated power user. Engineered a template repository providing AI-driven prompts and skills to bootstrap product integrations.",
      "End-to-End Product Leadership: Initiated and led the complete refactoring of the platform's onboarding experience, taking proactive ownership to drive the project from proof-of-concept to a successful production release.",
      "Developer Experience (DX) Infrastructure: Streamlined platform development by building a React component library that enforced Samsung's One Design guidelines to unify cross-brand UX, managing zero-break global NPM releases, and maintaining a JavaScript SDK autogenerated from OpenAPI specifications.",
    ],
    stack: [
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Docker",
      "Spinnaker",
      "Kubernetes",
      "Terraform",
      "GitHub Actions",
      "Jenkins",
      "Copilot",
      "Claude",
      "Gemini",
      "Python",
    ],
  },
  {
    company: "Samsung Research America",
    location: "San Francisco, CA",
    role: "Software Developer",
    period: "March 2018 – January 2020",
    bullets: [
      "Frontend Transition: Transitioned to web frontend development for ARTIK Cloud, instrumental in launching the Developer Workspace (a portal for managing SmartThings integrations).",
      "SDK Development: Developed a modern JavaScript SDK and specialized Starter Kits to improve the 3rd-party developer experience.",
      "Cross-Platform Maintenance: Maintained ARTIK Cloud's iOS developer tooling alongside web responsibilities.",
    ],
    stack: [
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Docker",
      "Spinnaker",
      "Kubernetes",
      "Swift",
      "App Store Connect",
      "TestFlight",
    ],
  },
  {
    company: "Samsung Strategy & Innovation Center",
    location: "San Francisco, CA",
    role: "iOS Developer",
    period: "June 2016 – March 2018",
    bullets: [
      "Executive Collaboration: Hired directly under executive leadership (Luc Julia, co-creator of Siri) to served as the lead iOS developer for ARTIK Cloud.",
      "App Engineering: Conceptualized and engineered the ARTIK Cloud iOS application from the ground up.",
      "Universal SDK: Developed and maintained a Universal Framework (SDK) enabling 3rd-party developers to build natively across iOS, tvOS, watchOS, and macOS.",
      "OS Optimization: Navigated strict Apple OS limitations (background task restrictions, location tracking) to ensure seamless application performance and reliable data syncing.",
    ],
    stack: ["Swift", "Objective-C", "App Store Connect", "TestFlight"],
  },
  {
    company: "Prism, Inc.",
    location: "San Francisco, CA",
    role: "iOS & Backend Developer",
    period: "October 2015 – May 2016",
    bullets: [
      "Full-Stack Engineering: Engineered an iOS application and its supporting backend architecture designed for automated, smart image classification.",
      "Computer Vision: Pioneered a computer vision–driven photo classification system predating native iOS Visual Search, utilizing OpenCV, Tesseract, and Python to identify apps from screenshots and execute Deep Link Lookups.",
      "API Architecture: Designed a highly performant and scalable REST API backed by a PostgreSQL database with Redis caching.",
    ],
    stack: ["Python", "Django", "PostgreSQL", "Redis", "SQLite", "tesseract-ocr", "OpenCV"],
  },
  {
    company: "Imprivata",
    location: "Santa Cruz, CA",
    role: "Android Developer (Capstone Partnership)",
    period: "January 2015 – August 2015",
    bullets: [
      "HIPAA-Compliant Mobile App: Developed an end-to-end encrypted Android application to facilitate secure, confidential document sharing between patients and medical professionals in strict accordance with HIPAA regulations.",
      "Data Synchronization: Architected the data synchronization flow using an internal SQLite database communicating with a Python/MySQL backend.",
    ],
    stack: ["Java", "Android Studio", "MySQL", "SQLite", "REST", "Python"],
  },
];

export const projects: {
  name: string;
  kind: string;
  period: string;
  summary: string;
  bullets: string[];
  stack: string[];
  githubUrl: string;
}[] = [
  {
    name: "Ralph-node",
    kind: "Personal Project",
    period: "April 2026",
    summary:
      "Built a fully custom, orchestrated AI development pipeline for Node.js from the ground up — no frameworks, no third-party dependencies. The project explores a single thesis: frontier models like Opus 4.7 can be used efficiently by routing tasks to the right model for the job, delivering production-quality output at a fraction of the cost.",
    bullets: [
      "Multi-Model Orchestration: Designed a routing layer that distributes work across 5 models from 4 providers — Opus 4.7 for planning, DeepSeek V4 Pro for test generation, MiniMax M2.7 for implementation, Opus 4.6 for supervision, and Gemma 4 (local) for summaries.",
      "Test-Gated Pipeline: Every phase is gated behind a test suite and reviewed through automated PR gates. Test generation acts as TDD backpressure — tests are written before implementation, forcing the pipeline to define correct behavior upfront rather than retrofit it.",
      "Ralph Loop: Implementation runs as a tight feedback loop: generate, test, fail, revise — cycling until the suite passes before surfacing output for review.",
      "Prompt Architecture: Engineered role-specific prompts tuned to each model's strengths and cost profile, demonstrating that economics and quality are not mutually exclusive when building AI-native development workflows.",
    ],
    stack: [
      "Claude",
      "OpenCode",
      "LM Studio",
      "Bash",
      "JavaScript",
      "TypeScript",
      "React",
      "Jest",
      "Playwright",
      "Biome",
      "GitHub Actions",
    ],
    githubUrl: "https://github.com/Laptopmini/ralph-node",
  },
];

export const education: { title: string; detail: string; status?: string }[] = [
  {
    title: "B.A. Computer Science",
    detail: "University of California, Santa Cruz (UCSC)",
  },
  {
    title: "Practical Prompt Engineering",
    detail: "Instructor: Sabrina Goldfarb (GitHub)",
    status: "Completed Dec 2025",
  },
  {
    title: "AI Agents Fundamentals, v2",
    detail: "Instructor: Scott Moss (Netflix)",
    status: "In Progress",
  },
];

export const aiCredit: {
  eyebrow: string;
  title: string;
  body: string;
  repoUrl: string;
  cta: string;
  steps: string[];
} = {
  eyebrow: "How this site was built",
  title: "Generated by ralph-node, an orchestrated AI pipeline.",
  body: "Built on a multi-model orchestration pipeline where a supervising model routes tasks to the right specialized model, with every phase gated behind a test suite. The Ralph loop continuously cycles through generate, test, and revision until the suite passes — ensuring production-quality output without manual intervention. Role-specific prompts tuned to each model's cost profile make quality and economics mutually exclusive.",
  repoUrl: "https://github.com/Laptopmini/ralph-node",
  cta: "View ralph-node on GitHub",
  steps: ["Blueprint", "PRD generation", "Test backpressure", "Ralph implementation loop"],
};
