import {
  aiCredit,
  education,
  experience,
  hero,
  profileSummary,
  projects,
  skills,
} from "../../src/content/resume";

describe("resume content", () => {
  describe("hero", () => {
    it("has correct eyebrow", () => {
      expect(hero.eyebrow).toBe("Senior Software Developer");
    });

    it("has correct title", () => {
      expect(hero.title).toBe("Paul-Valentin Mini");
    });

    it("has correct tagline", () => {
      expect(hero.tagline).toBe(
        "Building frontend platforms from concept to full-rate production. Even yours.",
      );
    });

    it("has correct cta", () => {
      expect(hero.cta).toBe("Get in touch");
    });

    it("has correct location", () => {
      expect(hero.location).toBe("San Francisco, CA");
    });

    it("has correct email", () => {
      expect(hero.email).toBe("paul@emini.com");
    });

    it("has correct phone", () => {
      expect(hero.phone).toBe("(415) 694-3616");
    });

    it("has correct linkedin", () => {
      expect(hero.linkedin).toBe("https://www.linkedin.com/in/pvmini");
    });

    it("has correct github", () => {
      expect(hero.github).toBe("https://github.com/Laptopmini");
    });
  });

  describe("profileSummary", () => {
    it("is a non-empty string", () => {
      expect(typeof profileSummary).toBe("string");
      expect(profileSummary.length).toBeGreaterThan(0);
    });

    it("mentions SmartThings", () => {
      expect(profileSummary).toContain("SmartThings");
    });
  });

  describe("skills", () => {
    it("has 4 skill categories", () => {
      expect(skills).toHaveLength(4);
    });

    it("each skill has category and items", () => {
      for (const skill of skills) {
        expect(skill).toHaveProperty("category");
        expect(skill).toHaveProperty("items");
        expect(Array.isArray(skill.items)).toBe(true);
        expect(skill.items.length).toBeGreaterThan(0);
      }
    });

    it("first skill is Frontend & Web", () => {
      expect(skills[0].category).toBe("Frontend & Web");
      expect(skills[0].items).toContain("JavaScript");
      expect(skills[0].items).toContain("React");
    });

    it("second skill is AI & Machine Learning", () => {
      expect(skills[1].category).toBe("AI & Machine Learning");
    });

    it("third skill is Infrastructure & DevOps", () => {
      expect(skills[2].category).toBe("Infrastructure & DevOps");
    });

    it("fourth skill is Backend & Mobile", () => {
      expect(skills[3].category).toBe("Backend & Mobile");
    });
  });

  describe("experience", () => {
    it("has 5 entries", () => {
      expect(experience).toHaveLength(5);
    });

    it("each entry has required fields", () => {
      for (const exp of experience) {
        expect(exp).toHaveProperty("company");
        expect(exp).toHaveProperty("location");
        expect(exp).toHaveProperty("role");
        expect(exp).toHaveProperty("period");
        expect(exp).toHaveProperty("bullets");
        expect(exp).toHaveProperty("stack");
        expect(Array.isArray(exp.bullets)).toBe(true);
        expect(Array.isArray(exp.stack)).toBe(true);
      }
    });

    it("first entry is SmartThings", () => {
      expect(experience[0].company).toBe("SmartThings, Inc.");
      expect(experience[0].role).toBe("Senior Software Developer");
      expect(experience[0].stack).toContain("React");
    });

    it("last entry is Imprivata", () => {
      expect(experience[4].company).toBe("Imprivata");
      expect(experience[4].location).toBe("Santa Cruz, CA");
    });
  });

  describe("projects", () => {
    it("has 1 entry", () => {
      expect(projects).toHaveLength(1);
    });

    it("is ralph-node with correct fields", () => {
      const project = projects[0];
      expect(project.name).toBe("Ralph-node");
      expect(project.kind).toBe("Personal Project");
      expect(project.period).toBe("April 2026");
      expect(project.githubUrl).toBe("https://github.com/Laptopmini/ralph-node");
      expect(Array.isArray(project.bullets)).toBe(true);
      expect(project.bullets.length).toBeGreaterThanOrEqual(4);
      expect(Array.isArray(project.stack)).toBe(true);
    });
  });

  describe("education", () => {
    it("has at least 2 entries", () => {
      expect(education.length).toBeGreaterThanOrEqual(2);
    });

    it("each entry has title and detail", () => {
      for (const edu of education) {
        expect(edu).toHaveProperty("title");
        expect(edu).toHaveProperty("detail");
      }
    });

    it("first entry is B.A. Computer Science from UCSC", () => {
      expect(education[0].title).toBe("B.A. Computer Science");
      expect(education[0].detail).toContain("University of California, Santa Cruz");
    });
  });

  describe("aiCredit", () => {
    it("has correct eyebrow", () => {
      expect(aiCredit.eyebrow).toBe("How this site was built");
    });

    it("has correct title", () => {
      expect(aiCredit.title).toBe("Generated by ralph-node, an orchestrated AI pipeline.");
    });

    it("has a non-empty body", () => {
      expect(typeof aiCredit.body).toBe("string");
      expect(aiCredit.body.length).toBeGreaterThan(0);
    });

    it("has correct repoUrl", () => {
      expect(aiCredit.repoUrl).toBe("https://github.com/Laptopmini/ralph-node");
    });

    it("has correct cta", () => {
      expect(aiCredit.cta).toBe("View ralph-node on GitHub");
    });

    it("has 4 workflow steps", () => {
      expect(aiCredit.steps).toHaveLength(4);
      expect(aiCredit.steps[0]).toBe("Blueprint");
      expect(aiCredit.steps[1]).toBe("PRD generation");
      expect(aiCredit.steps[2]).toBe("Test backpressure");
      expect(aiCredit.steps[3]).toBe("Ralph implementation loop");
    });
  });
});
