import { render, screen } from "@testing-library/react";
import AICreditSection from "@/components/AICreditSection";

describe("AICreditSection", () => {
  it("renders the AI credit section", () => {
    render(<AICreditSection />);
    const section = screen.getByTestId("ai-credit");
    expect(section).toBeInTheDocument();
  });

  it("renders the eyebrow text", () => {
    render(<AICreditSection />);
    expect(screen.getByText("How this site was built")).toBeInTheDocument();
  });

  it("renders the title", () => {
    render(<AICreditSection />);
    expect(screen.getByText(/Generated by ralph-node/)).toBeInTheDocument();
  });

  it("renders the body text", () => {
    render(<AICreditSection />);
    expect(screen.getByText(/multi-model orchestration pipeline/)).toBeInTheDocument();
  });

  it("renders all four workflow steps in order", () => {
    render(<AICreditSection />);
    const steps = screen.getAllByRole("listitem");
    expect(steps).toHaveLength(4);
    expect(steps[0]).toHaveTextContent("01");
    expect(steps[0]).toHaveTextContent("Blueprint");
    expect(steps[1]).toHaveTextContent("02");
    expect(steps[1]).toHaveTextContent("PRD generation");
    expect(steps[2]).toHaveTextContent("03");
    expect(steps[2]).toHaveTextContent("Test backpressure");
    expect(steps[3]).toHaveTextContent("04");
    expect(steps[3]).toHaveTextContent("Ralph implementation loop");
  });

  it("renders a link to the repo", () => {
    render(<AICreditSection />);
    const link = screen.getByRole("link");
    expect(link).toHaveAttribute("href", "https://github.com/Laptopmini/ralph-node");
  });
});
